name: Deploy to GitHub Pages

on:
  # Trigger the workflow when pushing to the "main" branch or on a pull request
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  build-and-deploy:
    # Specify the type of runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies and build the project
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist # Ensure this matches your Vite output directory
