name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js (Ensure Node.js 18+ is used)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify Node.js version 18 or higher

      # Step 3: Install dependencies and build the project
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
